<?php

/**
 * @var Hackathon_AsyncIndex_Block_Adminhtml_Process_Stats $this
 */

?>
<div class="asyncindex-process-stats grid" style="width: 300px;">
    <table class="data">
        <?php foreach( $this->getPendingEventsPerProcess() as $code=>$count ): ?>
            <tr>
                <td><?php echo $code; ?></td>
                <td><?php echo $count; ?></td>
                <td><form action="<?php
                    echo $this->getUrl('adminhtml/asyncindex/index',
                        array(
                            '_current'     => true,
                            '_secure'      => false,
                            'process_code' => $code
                        )
                    );
                    ?>"><button class="button" type="submit">schedule reindex</button></form></td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>
